package es.cediant.database;
// Generated Dec 5, 2012 2:09:29 PM by Hibernate Tools 3.2.1.GA



/**
 * Serie generated by hbm2java
 */
public class Serie  implements java.io.Serializable {


     private Integer idserie;
     private String name;
     private int time;
     private int data;
     private String comment;

    public Serie() {
    }

	
    public Serie(String name, int time, int data) {
        this.name = name;
        this.time = time;
        this.data = data;
    }
    public Serie(String name, int time, int data, String comment) {
       this.name = name;
       this.time = time;
       this.data = data;
       this.comment = comment;
    }
   
    public Integer getIdserie() {
        return this.idserie;
    }
    
    public void setIdserie(Integer idserie) {
        this.idserie = idserie;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public int getTime() {
        return this.time;
    }
    
    public void setTime(int time) {
        this.time = time;
    }
    public int getData() {
        return this.data;
    }
    
    public void setData(int data) {
        this.data = data;
    }
    public String getComment() {
        return this.comment;
    }
    
    public void setComment(String comment) {
        this.comment = comment;
    }




}


