package es.cediant.database;
// Generated Dec 11, 2012 5:35:11 PM by Hibernate Tools 3.2.1.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
//import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Serie generated by hbm2java
 */
@Entity
@Table(name="serie", catalog="webdb")
public class Serie  implements java.io.Serializable {
    
    private static final long serialVersionUID = 1L;

    private Integer idserie;
    private String name;
    private int time;
    private int data;
    private String comment;

    public Serie() {
    }
	
    public Serie(String name, int time, int data) {
        this.name = name;
        this.time = time;
        this.data = data;
    }
    public Serie(String name, int time, int data, String comment) {
       this.name = name;
       this.time = time;
       this.data = data;
       this.comment = comment;
    }
   
    @Id //@GeneratedValue(strategy=IDENTITY)    
    @Column(name="idserie", unique=true, nullable=false)
    public Integer getIdserie() {
        return this.idserie;
    }
    
    public void setIdserie(Integer idserie) {
        this.idserie = idserie;
    }
    
    @Column(name="name", nullable=false, length=45)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    
    @Column(name="time", nullable=false)
    public int getTime() {
        return this.time;
    }
    
    public void setTime(int time) {
        this.time = time;
    }
    
    @Column(name="data", nullable=false)
    public int getData() {
        return this.data;
    }
    
    public void setData(int data) {
        this.data = data;
    }
    
    @Column(name="comment", length=45)
    public String getComment() {
        return this.comment;
    }
    
    public void setComment(String comment) {
        this.comment = comment;
    }

}


