package es.cediant.database;
// Generated Nov 16, 2012 1:32:27 PM by Hibernate Tools 3.2.1.GA



/**
 * UsersId generated by hbm2java
 */
public class UsersId  implements java.io.Serializable {
    private static final long serialVersionUID = 3881993269831987739L;


     private int idusers;
     private String username;

    public UsersId() {
    }

    public UsersId(int idusers, String username) {
       this.idusers = idusers;
       this.username = username;
    }
   
    public int getIdusers() {
        return this.idusers;
    }
    
    public void setIdusers(int idusers) {
        this.idusers = idusers;
    }
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof UsersId) ) return false;
		 UsersId castOther = ( UsersId ) other; 
         
		 return (this.getIdusers()==castOther.getIdusers())
 && ( (this.getUsername()==castOther.getUsername()) || ( this.getUsername()!=null && castOther.getUsername()!=null && this.getUsername().equals(castOther.getUsername()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getIdusers();
         result = 37 * result + ( getUsername() == null ? 0 : this.getUsername().hashCode() );
         return result;
   }   


}


