package es.cediant.database;
// Generated Nov 16, 2012 1:32:27 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * Users generated by hbm2java
 */
public class Users  implements java.io.Serializable {
    private static final long serialVersionUID = -253490014843160029L;


     private UsersId id;
     private String password;
     private Date lastConnection;

    public Users() {
    }

	
    public Users(UsersId id, String password) {
        this.id = id;
        this.password = password;
    }
    public Users(UsersId id, String password, Date lastConnection) {
       this.id = id;
       this.password = password;
       this.lastConnection = lastConnection;
    }
   
    public UsersId getId() {
        return this.id;
    }
    
    public void setId(UsersId id) {
        this.id = id;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public Date getLastConnection() {
        return this.lastConnection;
    }
    
    public void setLastConnection(Date lastConnection) {
        this.lastConnection = lastConnection;
    }




}


